### ISSUE TITLE
Blur effect is not applied when the background is translucent

### ISSUE THREAD

**Issue by EldoDebug** [amnweb/blur-menu-vscode#6]
"workbench.colorCustomizations": {
    "editor.background": "#00000000",
}

For example, the blur effect will not be applied when set like this
I don't understand how it works, but is it possible to blur only the text on a translucent background?

**Comment by amnweb** [comment]
Blur does not apply to editor. For this you will need some extensions like APC.

**Comment by EldoDebug** [comment]
My explanation was poor
Yes, that's right
I used apc to make the background transparent
However, if make the editor background semi-transparent, the context menu blur disappears

**Comment by EldoDebug** [comment]
video
https://github.com/user-attachments/assets/9ab476be-3ac7-4114-a96e-90d44ffcee4c

**Comment by amnweb** [comment]
Blur for menu uses a backdrop filter; here is the problem because the filter cannot work if you have a transparent background, so in this way it is not possible to have both. I have a plan to archive this extension and move everything to https://github.com/amnweb/SpaceBox-UI-Enhancer. After that, I will check what I can integrate there and what is possible to make, but also we need to wait for the new VSCode release and the new Electron version, which is already included in the Insider version. However, as I can see, there are some problems; maybe they will be fixed when they release the stable version.

**Comment by EldoDebug** [comment]
I see. I understand!
Thank you so much
